# Generated by Django 5.1.4 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Input Brand example(Ford)', max_length=100, verbose_name='Brand')),
                ('model', models.CharField(help_text='Input Model name example(Focus)', max_length=100, verbose_name='Model')),
                ('years', models.DateField(help_text='Choose made date', max_length=100, verbose_name='Years')),
                ('fuel', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('choose', 'Unknown')], default='choose', help_text='Choose Fuel type', max_length=20)),
                ('engine', models.CharField(help_text='Input Brand example(2.0TDI)', max_length=100, verbose_name='Engine')),
                ('power', models.IntegerField(help_text='Input power example(77)', verbose_name='Power KW')),
                ('gearbox', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('choose', 'Unknown')], default='choose', help_text='Choose gearbox type', max_length=20)),
                ('color', models.CharField(help_text='Input Color Code example(LC5J)', max_length=20, verbose_name='Color')),
                ('body_type', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('choose', 'Unknown')], default='choose', help_text='Choose body type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_oem', models.CharField(help_text='Input OEM Code example(A1237300705)', max_length=100, verbose_name='Part OEM')),
                ('condition', models.CharField(blank=True, choices=[('new', 'NEW'), ('used', 'USED'), ('choose', '')], default='choose', help_text='Choose condition part', max_length=20)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('rear-left', 'Rear-Left'), ('rear-right', 'Rear-Right'), ('choose', '')], default='choose', help_text='Choose part side', max_length=20)),
                ('price', models.FloatField(help_text='Input part price example(199.99)', max_length=100, verbose_name='Price')),
            ],
        ),
    ]
