# Generated by Django 5.1.4 on 2024-12-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_oem', models.CharField(help_text='Input OEM Code example(A1237300705)', max_length=100, verbose_name='Part OEM')),
                ('condition', models.CharField(blank=True, choices=[('new', 'NEW'), ('used', 'USED'), ('choose', '')], default='choose', help_text='Choose condition part', max_length=20)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('rear-left', 'Rear-Left'), ('rear-right', 'Rear-Right'), ('choose', '')], default='choose', help_text='Choose part side', max_length=20)),
                ('price', models.FloatField(help_text='Input part price example(199.99)', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(blank=True, choices=[('air_condition', 'Air conditioning-heating system/radiators'), ('body_parts', 'Body parts'), ('brake_system', 'Brake system'), ('electronic_system', 'Electronic system'), ('door', 'Door'), ('engine', 'Engine'), ('front_body', 'Front body parts'), ('rear_body', 'Rear body parts'), ('front_axle', 'Front axle'), ('rear_axle', 'Rear axle'), ('fuel_system', 'Fuel mixture system'), ('exhaust_system', 'Gas exhaust system'), ('gearbox', 'Gearbox/clutch/transmission'), ('glass', 'Glass'), ('headlight_system', 'Headlight washing/cleaning system'), ('other_parts', 'Other parts'), ('wheels', 'Wheels/tires/caps'), ('choose', '')], default='choose', help_text='Choose part type', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.AlterField(
            model_name='car',
            name='years',
            field=models.CharField(help_text='Input made date example(2020)', max_length=4, null=True, verbose_name='Years'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(help_text='Choose part type', on_delete=django.db.models.deletion.CASCADE, to='carparts.parttype'),
        ),
    ]
