# Generated by Django 5.1.4 on 2024-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0002_part_parttype_delete_parts_alter_car_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='parts',
            field=models.ManyToManyField(blank=True, help_text='Link parts to this car', related_name='cars', to='carparts.part'),
        ),
    ]
