# Generated by Django 5.1.4 on 2024-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0003_car_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('cabriolet', 'Cabriolet'), ('coupe', 'Coupe'), ('sedan', 'Sedan'), ('station', 'Station'), ('hatchback', 'Hatchback'), ('choose', 'Unknown')], default='choose', help_text='Choose body type', max_length=20),
        ),
    ]
