# Generated by Django 5.1.4 on 2024-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0004_alter_car_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_description',
            field=models.CharField(help_text='Write part description', max_length=250, null=True, verbose_name='Part description'),
        ),
    ]
