# Generated by Django 5.1.4 on 2024-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0005_car_car_cover_part_part_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_cover',
            field=models.ImageField(default='part_pics/no-image.jpg', upload_to='part_pics'),
        ),
    ]
