# Generated by Django 5.1.4 on 2024-12-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0006_part_part_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_cover',
            new_name='part_picture',
        ),
    ]
