# Generated by Django 5.1.4 on 2024-12-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0007_rename_part_cover_part_part_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Input Brand example(Ford)', max_length=100, verbose_name='Brand')),
                ('model', models.CharField(help_text='Input Model name example(Focus)', max_length=100, verbose_name='Model')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carmodel', to='carparts.carmodel'),
        ),
    ]
