# Generated by Django 5.1.4 on 2024-12-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0008_carmodel_remove_car_brand_remove_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carparts.carmodel'),
        ),
    ]
