# Generated by Django 5.1.4 on 2024-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0009_alter_car_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.CharField(help_text='Write part name example(Audi front-driver doors)', max_length=100, null=True, verbose_name='Part name'),
        ),
    ]
