# Generated by Django 5.1.4 on 2024-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0010_part_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_cover',
            field=models.ImageField(blank=True, default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover'),
        ),
    ]
