# Generated by Django 5.1.4 on 2024-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0014_alter_parttype_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttype',
            name='part_type',
            field=models.CharField(blank=True, choices=[('air_condition', 'Air conditioning-heating system/radiators'), ('body_parts', 'Body parts'), ('brake_system', 'Brake system'), ('electronic_system', 'Electronic system'), ('door', 'Door'), ('engine', 'Engine'), ('front_body', 'Front body parts'), ('rear_body', 'Rear body parts'), ('front_axle', 'Front axle'), ('rear_axle', 'Rear axle'), ('fuel_system', 'Fuel mixture system'), ('exhaust_system', 'Gas exhaust system'), ('gearbox', 'Gearbox/clutch/transmission'), ('glass', 'Glass'), ('headlight_system', 'Headlight washing/cleaning system'), ('lighting_system', 'Lighting system'), ('other_parts', 'Other parts'), ('wheels', 'Wheels/tires/caps'), ('choose', '')], default='choose', help_text='Choose part type', max_length=100, null=True),
        ),
    ]
