# Generated by Django 5.1.4 on 2024-12-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0015_alter_parttype_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_picture',
            field=models.ImageField(blank=True, default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover'),
        ),
    ]
