# Generated by Django 5.1.4 on 2025-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0017_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='part',
            name='part_picture_2',
            field=models.ImageField(blank=True, default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover2'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_picture_3',
            field=models.ImageField(blank=True, default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover3'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_picture_4',
            field=models.ImageField(blank=True, default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover4'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_progress',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('working', 'Working'), ('stuck', 'Stuck'), ('pause', 'Pause'), ('almost done', 'Almost Done'), ('done', 'Done')], default='new', help_text='Progressive', max_length=100, null=True),
        ),
    ]
