# Generated by Django 5.1.4 on 2025-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0022_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Input phone number example(+37062222222)', max_length=100, null=True, verbose_name='Phone number'),
        ),
    ]
