# Generated by Django 5.1.4 on 2025-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0023_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_picture',
            field=models.ImageField(default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover'),
        ),
    ]
