# Generated by Django 5.1.4 on 2025-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0024_alter_part_part_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('Unknown', 'Unknown')], default='Unknown', help_text='Choose gearbox type', max_length=20),
        ),
    ]
