# Generated by Django 5.1.4 on 2025-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0025_alter_car_gearbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('cabriolet', 'Cabriolet'), ('coupe', 'Coupe'), ('sedan', 'Sedan'), ('station', 'Station'), ('hatchback', 'Hatchback'), ('Unknown', 'Unknown')], default='choose', help_text='Choose body type', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'NEW'), ('used', 'USED'), ('damaged', 'DAMAGED'), ('choose', '')], default='choose', help_text='Choose condition part', max_length=20),
        ),
    ]
