# Generated by Django 5.1.4 on 2025-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0028_alter_parttype_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'NEW'), ('used', 'USED'), ('damaged', 'DAMAGED')], help_text='Choose condition part', max_length=20),
        ),
    ]
