# Generated by Django 5.1.4 on 2025-01-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0030_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='part',
        ),
    ]
