# Generated by Django 5.1.4 on 2025-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0031_rename_product_cartitem_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_code',
            field=models.CharField(help_text='Input Engine code', max_length=100, null=True, verbose_name='Engine Code'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox_code',
            field=models.CharField(help_text='Input Gearbox code', max_length=100, null=True, verbose_name='Gearbox Code'),
        ),
    ]
