# Generated by Django 5.1.4 on 2025-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0033_alter_car_gearbox_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('cabriolet', 'Cabriolet'), ('coupe', 'Coupe'), ('sedan', 'Sedan'), ('station', 'Station'), ('hatchback', 'Hatchback'), ('Unknown', 'Unknown')], default='Unknown', help_text='Choose body type', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_code',
            field=models.CharField(blank=True, help_text='Input Engine code', max_length=100, verbose_name='Engine Code'),
        ),
    ]
