# Generated by Django 5.1.4 on 2025-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0034_alter_car_body_type_alter_car_engine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_cover',
            field=models.ImageField(default='part_pics/no-image.jpg', null=True, upload_to='covers', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='profile_pics/no-image.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
